#201600282 엄기산

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell. ast_node_interactivity = "all"

In [2]:
import numpy as np
import math

In [3]:
x0 = 1

U1 = np.array([[-0.3,1,1.2],[1.6,-1,-1.1]])
U2 = np.array([[1,1,-1],[0.7,0.5,1]])
U3 = np.array([[0.5,-0.8,1],[-0.1,0.3,0.4]])
U4 = np.array([[1,0.1,-0.2],[-0.2,1.3,-0.4]])

In [4]:
input = np.array([[x0],[1],[0]])

In [5]:
target = np.array([[0],[1]])

In [6]:
U1
U2
U3
U4

array([[-0.3,  1. ,  1.2],
       [ 1.6, -1. , -1.1]])

array([[ 1. ,  1. , -1. ],
       [ 0.7,  0.5,  1. ]])

array([[ 0.5, -0.8,  1. ],
       [-0.1,  0.3,  0.4]])

array([[ 1. ,  0.1, -0.2],
       [-0.2,  1.3, -0.4]])

In [7]:
def activation(x):
    return 1 / (1 + np.exp(-x))

#가중치 변경 전 ReLU 사용시 오차 확인

In [8]:
z1 = np.dot(U1,input)
o1 = activation(z1)

z2 = np.dot(U2,np.insert(o1,0,x0))
o2 = activation(z2)

z3 = np.dot(U3,np.insert(o2,0,x0))
o3 = activation(z3)

z4 = np.dot(U4,np.insert(o3,0,x0))
o4 = activation(z4)

o4

array([0.72021291, 0.60807077])

In [9]:
e1 = target - o4.reshape(2,1)
e1 = np.square(e1)
e1 = e1.sum(0) /2
e1

array([0.33615758])

# 가중치 변경 후 ReLU 사용시 오차 확인

In [10]:
U3[0][2] = 0.9

In [11]:
z1 = np.dot(U1,input)
o1 = activation(z1)

z2 = np.dot(U2,np.insert(o1,0,x0))
o2 = activation(z2)

z3 = np.dot(U3,np.insert(o2,0,x0))
o3 = activation(z3)

z4 = np.dot(U4,np.insert(o3,0,x0))
o4 = activation(z4)

o4

array([0.7198378 , 0.60229099])

In [12]:
e2 = target - o4.reshape(2,1)
e2 = np.square(e2)
e2 = e2.sum(0) /2
e2

array([0.33816946])

In [13]:
e1 > e2

array([False])