In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
torch.manual_seed(0)

In [3]:
z = torch.FloatTensor([1,2,3])

In [4]:
z

tensor([1., 2., 3.])

In [5]:
hypothesis = F.softmax(z,dim=0)

여기서 dim 은 방향을 의미

0일 경우에는 아래쪽으로 확률 변수 합하면 1

1일 경우에는 오른쪽으로 확률 변수 합하면 1

즉 차원으로 생각하면 됨  1차원 텐서이므로 dim 0

2차원 텐서 입력받으면 dim을 1로 주면서 2차원 텐서의 요소중 1차원별로 확률변수 합하면 1

In [6]:
hypothesis

tensor([0.0900, 0.2447, 0.6652])

In [7]:
from numpy import exp

In [8]:
exp(1)/(exp(1)+exp(2)+exp(3))

0.09003057317038046

In [9]:
exp(2)/(exp(1)+exp(2)+exp(3))

0.24472847105479767

In [10]:
exp(3)/(exp(1)+exp(2)+exp(3))

0.6652409557748219

In [11]:
z = torch.rand(3,5, requires_grad = True)

In [12]:
hypothesis = F.softmax(z, dim= 1)

In [13]:
hypothesis

tensor([[0.2222, 0.2917, 0.1478, 0.1544, 0.1840],
        [0.2000, 0.1732, 0.2600, 0.1673, 0.1996],
        [0.2194, 0.2313, 0.1583, 0.1833, 0.2077]], grad_fn=<SoftmaxBackward0>)

In [14]:
z

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939]], requires_grad=True)

In [15]:
y = torch.randint(5,(3,)).long()

radnint(5,(3,) 은 0~4 까지의 숫자중 3개를 뽑으라는 의미

In [16]:
y

tensor([1, 1, 3])

In [17]:
y_one_hot = torch.zeros_like(hypothesis)

In [18]:
y_one_hot

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [19]:
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.]])

scatter_ 설명

첫번쨰 변수 = 

두번쨰 변수 = 위치

세번째 변수 = 어떤 것을 넣을것인지

In [20]:
cost = (y_one_hot * -torch.log(hypothesis))

크로스 엔트로피를 one hot 코드와 같이 사용하면 1되어있는 부분만 가져다 쓰기 때문에 위와 같은 식이 나옴

뒤에 곱해져있는것이 logQ(x) 라 생각하면 됨

In [21]:
cost

tensor([[0.0000, 1.2322, 0.0000, 0.0000, 0.0000],
        [0.0000, 1.7536, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 1.6968, 0.0000]], grad_fn=<MulBackward0>)

In [22]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()

In [23]:
cost

tensor(1.5608, grad_fn=<MeanBackward0>)

In [24]:
torch.log(F.softmax(z,dim=1))

tensor([[-1.5041, -1.2322, -1.9119, -1.8684, -1.6930],
        [-1.6096, -1.7536, -1.3472, -1.7880, -1.6113],
        [-1.5167, -1.4639, -1.8433, -1.6968, -1.5717]], grad_fn=<LogBackward0>)

In [25]:
F.log_softmax(z,dim=1)

tensor([[-1.5041, -1.2322, -1.9119, -1.8684, -1.6930],
        [-1.6096, -1.7536, -1.3472, -1.7880, -1.6113],
        [-1.5167, -1.4639, -1.8433, -1.6968, -1.5717]],
       grad_fn=<LogSoftmaxBackward0>)

In [26]:
(y_one_hot * -torch.log(F.softmax(z,dim=1))).sum(dim=1).mean()

tensor(1.5608, grad_fn=<MeanBackward0>)

In [27]:
F.nll_loss(F.log_softmax(z,dim=1),y)

tensor(1.5608, grad_fn=<NllLossBackward0>)

negative log likehood 손실 = nll

In [28]:
F.cross_entropy(z,y)

tensor(1.5608, grad_fn=<NllLossBackward0>)