In [1]:
import numpy as np

In [11]:
arr = np.arange(32).reshape(8,4)

In [12]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [15]:
arr[[0,1,2,3],[3,2,1,0]]

array([ 3,  6,  9, 12])

201600282 엄기산

In [22]:
arr1 =np.arange(4).reshape((2,2))
arr1

array([[0, 1],
       [2, 3]])

In [23]:
np.dot(arr1,np.eye(2))


array([[0., 1.],
       [2., 3.]])

In [24]:
np.dot(np.eye(2),arr1)

array([[0., 1.],
       [2., 3.]])

행렬의 곱에서 단위행렬은 항등원이기 때문에 결과가 같게 나옴.
201600282 엄기산

In [25]:
arr2 = np.arange(24).reshape((2,3,4))
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
arr2.transpose(2,1,0)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

201600282 엄기산