In [9]:
import numpy as np

In [10]:
from numpy.linalg import inv, qr

In [13]:
X2 = np.eye(2)
X2


array([[1., 0.],
       [0., 1.]])

In [14]:
inv(X2)

array([[1., 0.],
       [0., 1.]])

In [20]:
X = np.array([1,2,3,4]).reshape(2,2)
X

array([[1, 2],
       [3, 4]])

In [21]:
X@X2

array([[1., 2.],
       [3., 4.]])

In [ ]:
np.dot(X,X2)

In [22]:
X2@X

array([[1., 2.],
       [3., 4.]])

In [24]:
np.dot(X2,X)

array([[1., 2.],
       [3., 4.]])